### ISSUE TITLE
Weather command : specify location

### ISSUE THREAD

**Issue by Antoine-Bergerault** [huguesdevimeux/IC-BOT#1]
Il faudrait pouvoir spécifier la location utilisée pour la commande de météo, tout en gardant Lausanne comme ville par défaut

**Comment by huguesdevimeux** [comment]
C'est ce que je voulais faire, mais que je n'ai pas fait faute de temps. Les PRs sont toujours ouvertes :D 

L'API utilisée pour la météo supporte parfaitement ceci puisqu’un paramètre du nom de la ville est passé dans la requête.
