### ISSUE TITLE
Reacting to direct messages

### ISSUE THREAD

**Issue by Antoine-Bergerault** [huguesdevimeux/IC-BOT#2]
Il pourrait être bien que le bot puisse interagir avec les messages envoyés directement. Voici deux possibilités :

1) Il répond simplement `le bot est uniquement utilisable sur un serveur`

2) Le bot n'a plus de tag et nous pouvons l'utiliser normalement. Cela pourrait notamment être utile pour lancer la commande `help`

**Comment by huguesdevimeux** [comment]
Merci pour la suggestion, c'est une bonne idée. 

En revanche je ne suis pas sûr de comprendre ceci ; 


>     2\. Le bot n'a plus de tag et nous pouvons l'utiliser normalement. Cela pourrait notamment être utile pour lancer la commande `help`

**Comment by Antoine-Bergerault** [comment]
Au lieu d'écrire `!ic help` il suffirait d'écrire `help`. Il n'y a pas d'intérêt à préciser au bot que l'on s'adresse à lui lorsqu'on utilise les messages privés.

**Comment by huguesdevimeux** [comment]
Ah, je vois. 

En vrai je ne vois pas l'intérêt, puisque le bot est précisément fait pour être utilisé dans le serveur de promo :/ 

En revanche, l'idée du message est bonne et je vais l'implementer.

**Comment by huguesdevimeux** [comment]
Fermé par le 7c7ed080060ee5cc8d5499fc412ed4019a90e268.
